spring:
  datasource:
    url: jdbc:mysql://localhost:3306/expense_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

server:
  port: 8080

app:
  jwt:
    secret: my_super_secret_key_change_it
    expiration-ms: 86400000

logging:
  level:
    root: INFO
